<?php
/**
 * Created by PhpStorm.
 * User: zhangxiaohei
 * Date: 2020/3/31
 * Time: 22:58
 */

namespace app\index\controller;


use app\common\controller\Common;
use think\Request;

class Basis extends Common
{

    public  function __construct(Request $request)
    {


        //读取配置
        $index_view_path = \app\common\model\Config::where(['name'=>'index_view_path'])->find()->toArray();
        $index_view_path = $index_view_path?$index_view_path['value']:'view';
        config('template.view_path',APP_PATH.$request->module().DS.$index_view_path.DS);


        //读取配置 前台域名白名单
        $index_domain_white_list = \app\common\model\Config::where(['name'=>'index_domain_white_list'])->find()->toArray();
        if($index_domain_white_list){
            if($index_domain_white_list['value']){
//                var_dump($_SERVER['HTTP_HOST']);die();
                if($index_domain_white_list['value'] != $_SERVER['HTTP_HOST'] ){
                    header("HTTP/1.0 404 Not Found");//使HTTP返回404状态码
                    die();
                }
            }
        }


        parent::__construct($request);
    }

//    public function fetch($template = '', $vars = [], $replace = [], $config = [])
//    {
//        //这里读取配置 判断配置的是哪个模板
//        return parent::fetch(APP_PATH.request()->module().'/view/demo/index.html', $vars, $replace, $config); // TODO: Change the autogenerated stub
//    }

}
